config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'images/new'
  get 'images/create'
  get 'images/destroy'
  get 'images/index'
  resources :images
  resources :categories, only: [:show, :index]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :category
  validates :image, presence: true
  validate :year_validation
  
  mount_uploader :image, ImageUploader
  
  private 
    def year_validation
      if self.image_year && ((self.image_year < 2000) || (self.image_year > Date.today.year))
        self.errors.add_to_base("Not valid year of creation")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @portrait = Image.find_by(category_id: 1)
    @illustration = Image.find_by(category_id: 2)
    @still_life = Image.find_by(category_id: 3)
  end
  
  def show
    @images = Image.where(category_id: params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def works
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/index.html.erb
<div class="container works-callout d-flex justify-content-center align-items-md-center">
  <div class="row categories-row">
    <% if @portrait %>
      <div class="col-lg-4 category d-flex justify-content-center">
        <%= image_tag(@portrait.image.url, class:'category-link-img rounded-circle') %>
        <div class="categories-link-text d-flex align-items-center justify-content-center">
          <%= link_to "Portraits", category_path(1) %>
        </div>
      </div>
    <% end %>
    <% if @illustration %>
      <div class="col-lg-4 category d-flex justify-content-center">
        <%= image_tag(@illustration.image.url, class:'category-link-img rounded-circle') %>
        <div class="categories-link-text d-flex align-items-center justify-content-center">
          <%= link_to "Illustrations", category_path(2) %>
        </div>
      </div>
    <% end %>
    <% if @still_life %>
      <div class="col-lg-4 category d-flex justify-content-center">
          <%= image_tag(@still_life.image.url, class:'category-link-img rounded-circle') %>
          <div class="categories-link-text d-flex align-items-center justify-content-center">
            <%= link_to "Still life and paysages", category_path(3) %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container-fluid category-callout">
  <h1 class="category-name text-center"><%= Category.find(@images.first.category_id).name %></h1>
  <div class="row">
      <% @images.each do |image| %>
        <div class="col-lg-4 col-md-6 col-sm-12 d-flex justify-content-center artwork-and-text">
            <% if image.image_title != "" or image.image_description != "" or image.image_year %>
              <%= image_tag(image.image.url, class: 'artwork') %>
              <div class="artwork-text d-flex justify-content-center align-items-center">
                <%= link_to image.image.url, data: {lightbox: 'artworks', title: image.image_title} do %>
                  <ul class="list-unstyled">
                    <% if image.image_title != "" %>
                      <%= content_tag(:li, image.image_title, class: 'text-center artwork-title') %>
                    <% end %>
                    <% if image.image_description != "" %>
                      <hr/><%= content_tag(:li, image.image_description, class: 'text-center artwork-description') %><hr/>
                    <% end %>
                    <% if image.image_year %>
                      <%= content_tag(:li, image.image_year, class: 'text-center artwork-year') %>
                    <% end %>
                  </ul>
                <% end %>
              </div>
            <% else %>
              <%= link_to image.image.url, data: {lightbox: 'artworks', title: image.image_title} do %>
                <%= image_tag(image.image.url, class: 'artwork') %>
              <% end %>
            <% end %>
            <%= image_tag("https://nogellos-portfolio-assets.s3.amazonaws.com/assets/ducttape-img.png", class: 'top-tape') %>
            <%= image_tag("https://nogellos-portfolio-assets.s3.amazonaws.com/assets/ducttape-img.png", class: 'bottom-tape') %>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NogellosPortfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Caveat:400,700|Roboto&amp;subset=cyrillic" rel="stylesheet">
    <link rel="shortcut icon" href="https://s3.amazonaws.com/nogellos-portfolio-assets/assets/paint-brush-icon-img.png" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless current_page?('/') %>
      <%= image_tag("https://nogellos-portfolio-assets.s3.amazonaws.com/assets/corner-leaves-img.png", class: "corner-leaves") %>
      <nav class="navbar navbar-expand-lg navbar-light">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-pencil"></i>
          Nogellos
          <i class="fa fa-paint-brush"></i>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Works", categories_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container about-callout">
  <div class="row">
    <div class="col-lg-8 offset-lg-2 col-md-12 text-center">
      <h1 class="info-title">Hello everybody! My name is Sasha Petrash!</h1><br/>
      <p class="info">Contact me via Instagram Direct or via e-mail: <span class="email">nogellos@gmail.com</span></p>
      <div class="row social-networks">
        <div class="col-md-2 offset-md-2">
          <%= link_to "https://www.instagram.com/nogellos/", class: "link" do %>
            <i class="fa fa-instagram"></i><br/>
          <% end %>
        </div>
        <div class="col-md-2 offset-md-4">
          <%= link_to "https://www.facebook.com/profile.php?id=100017149932111", class: "link" do %>
            <i class="fa fa-facebook-square"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container home-callout">
  <div class="row">
    <div class="col-lg-3 col-md-12">
      <%= image_tag("https://nogellos-portfolio-assets.s3.amazonaws.com/assets/leaves-img.png", class: 'leaves-img-works') %>
      <%= link_to "works", categories_path, class: 'link works' %>
      <div class="portfolio-box">
        <h1>port</h1><br/>
        <h1>fol</h1><br/>
        <h1>io</h1>
      </div>
    </div>
    <div class="col-lg-6 col-md-12 d-flex justify-content-center align-self-center portrait-and-text">
      <%= image_tag("https://s3.amazonaws.com/nogellos-portfolio-assets/assets/portrait-img.jpg", class:'portrait-img rounded-circle') %>
      <div class="img-text d-flex align-items-center justify-content-center">
        <%= link_to "About Me", about_path, class: 'text-center' %>
      </div>
    </div>
    <div class="col-lg-3 col-md-12"> 
      <div class="d-flex justify-content-center">
        <%= image_tag("https://nogellos-portfolio-assets.s3.amazonaws.com/assets/nogellos-img.png", class:'nogellos-img') %>
      </div>
      <%= link_to "my instagram", "https://www.instagram.com/nogellos/", class: 'link my-inst' %>
      <%= image_tag("https://nogellos-portfolio-assets.s3.amazonaws.com/assets/leaves-img.png", class: 'leaves-img-my-inst') %>
    </div>
  </div>
</div>

app/views/pages/works.html.erb
<div class="container works-callout d-flex align-items-center justify-content-center">
  <div class="row categories-row ">
    <div class="col-md-4 d-flex justify-content-center">
      <div class="category d-flex align-items-center justify-content-center">
        <%= link_to "Portraits", "#" %>
      </div>
    </div>
    <div class="col-md-4 d-flex justify-content-center">
      <div class="category d-flex align-items-center justify-content-center">
        <%= link_to "Illustrations", "#" %>
      </div>
    </div>
    <div class="col-md-4 d-flex justify-content-center">
      <div class="category d-flex align-items-center justify-content-center">
        <%= link_to "Still life and paysages", "#" %>
      </div>
    </div>
  </div>
</div>